### ISSUE TITLE
Allow for data

### ISSUE THREAD

**Issue by ews-ffarella** [OctoPrint/mkdocs-site-urls#1]
Hi!
I am trying to embed a pdf like this

```md

<object data="site:arctifacts/my.pdf" style="width: 100%;height: 900px"></object>
```

Could you maybe try to modify theregex to add data to allow this?

Thank you!

**Comment by foosel** [comment]
Sure thing! I think I'll make the checked attributes configurable while at it, that way things get even more flexible 👍

**Comment by foosel** [comment]
There you go, should work now. I also added a docs site with an example page that now acts a bit as a test as well.

**Comment by ews-ffarella** [comment]
Works very well. Thanks for the effort 😄
